DELETE /api/roles/2/permissions/3 HTTP/1.1
User-Agent: insomnia/11.1.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiY2RjYXNhc2RAdWRpc3RyaXRhbC5lZHUuY28iLCJ1c2VySWQiOiI5ODc2NTQzMjEiLCJyb2xlcyI6WyJhZG1pbiIsInVzdWFyaW9fcHJlbWl1bSJdLCJpYXQiOjE3NTA4ODM5ODgsImV4cCI6MTc1MDg4NzU4OH0.4OHfK1yaZwl_ZzyUkP2DfOdPFAv0OLKBl5r_XqH2SEw
Host: localhost:3000

//Response:
HTTP/1.1 200 OK
{
	"message": "Permiso eliminado del rol correctamente"
}
