# A traves de este endoint se pueden acualizar las prefencias de notificaciones

PATCH http://localhost:3000/api/notification-settings
Auth Bearer Token, 

Body:
{
  "smsEnabled" : true
}

{
  "success": true,
  "data": {
    "id": 1,
    "emailEnabled": true,
    "smsEnabled": true,
    "whatsappEnabled": false,
    "phoneNumber": null
  },
  "message": "Configuración de notificaciones actualizada exitosamente"
}

Actualizo smsEnabled a true