PATCH /api/roles/7 HTTP/1.1
Content-Type: application/json
User-Agent: insomnia/11.1.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiY2RjYXNhc2RAdWRpc3RyaXRhbC5lZHUuY28iLCJ1c2VySWQiOiI5ODc2NTQzMjEiLCJyb2xlcyI6WyJhZG1pbiIsInVzdWFyaW9fcHJlbWl1bSJdLCJpYXQiOjE3NTA4ODAzMTEsImV4cCI6MTc1MDg4MzkxMX0.hlOlHxZvDnnlkEH6gBnOagaZ7bNjhX2Q1NxStH_S8SU
Host: localhost:3000
Content-Length: 78

{
  "description": "Rol actualizado para soporte",
  "permissions": [10, 11]
}

//response 200 OK

{
	"id": 7,
	"name": "soporte",
	"description": "Rol actualizado para soporte",
	"permissions": [
		{
			"id": 10,
			"name": "manage_watchlist"
		},
		{
			"id": 11,
			"name": "view_premium_reports"
		}
	]
}