#Actualizar las preferencias de las alertas sobre los mercados

PATCH http://localhost:3000/api/preferences/notifications-settings
Authorization: Bearer <token_de_usuario>

ej:

{
  "notify_daily_summary" : false
}

Response:

{
  "id": 1,
  "notify_open_close_markets": true,
  "notify_daily_summary": false,
  "notify_execute_orders": true,
  "notify_price_alerts": true,
  "last_change_time": "2025-06-28T04:52:10.147Z"
}