# Actualizar los canales de comunicacion (SMS, correo, whatsapp)

PATCH http://localhost:3000/api/preferences/mailing-settings
Authorization: Bearer <token_de_usuario>

ej:

{
  "sms_enabled" : true
}

Response:

{
  "id": 1,
  "email_enabled": true,
  "sms_enabled": true,
  "whatsapp_enabled": false,
  "phone_number": null,
  "last_change_time": "2025-06-28T04:56:16.375Z"
}