GET http://localhost:3000/api/accounts/balance
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDU3MzUwMDk0IiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsInJvbGVzIjpbXSwiaWF0IjoxNzUwOTY5OTk5LCJleHAiOjE3NTA5NzM1OTl9.CyaJTJZfg9ektahwf1_Se9n2vOKON-JehSufRV15PZU

