POST https://broker-api.sandbox.alpaca.markets/v1/accounts/
Authorization: Basic Q0tTTEFYQ1cwNU83Q0pZR0FFNUs6MWx6NWVJWTlwWm5zemdtS1Z3THJhaFlGdUtCTWZMV0Jwb3JFZjNXTA==
{
  "contact": {
    "email_address": "santyavella21@gmail.com",
    "phone_number": "+573123551663",
    "street_address": "cll45",
    "city": "Bogota D.C"
  },
  "identity": {
    "given_name": "Santiago",
    "family_name": "Avella",
    "date_of_birth": "2003-12-20",
    "tax_id": "1058350094",
    "tax_id_type": "COL_NIT",
    "country_of_tax_residence": "COL"
  },
  "disclosures": {
    "is_control_person": false,
    "is_affiliated_exchange_or_finra": false,
    "is_politically_exposed": false,
    "immediate_family_exposed": false
  },
    "agreements": [
    {
      "agreement": "customer_agreement",
      "signed_at": "2025-05-30T15:36:42.264256459Z",
      "ip_address": "127.0.0.1"
    }
  ]
}