POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWF0IjoxNzQ5MTc1ODAwLCJleHAiOjE3NDkxNzk0MDB9.1wTWSPz-4hIxapY_Ro6f1u2bSmlwaXDzZ9LTQwWo1zE

{
  "identity_document": "1057350094",
  "first_name": "John",
  "last_name": "Doeh",
  "phone": "+573123551663",
  "birthdate": "2003-12-20",
  "address": "cll45", 
  "account": {
    "email": "johndoe@gmail.com",
    "password": "A1#asdasadasda"
  }
}