
export const defaultAccountAlpacaEnum = {
    CONTACT_CITY : 'Bogota D.C',
    IDENTITY_TAX_ID : 'COL_NIT',
    COUNTRY_OF_TAX_RESIDENCE : 'COL',
    DISCLOSURES_IS_CONTROL_PERSON : false,
    DISCLOSURES_IS_AFFILIATED : false,
    DISCLOSURES_IS_POLITICALLY_EXPOSED : false,
    DISCLOSURES_IS_IMMEDIATE_FAMILY_EXPOSED : false,
    AGREEMENTS_AGREEMENT : 'customer_agreement',
    AGREEMENTS_AGREEMENT_IP_ADDRESS : '127.0.0.1'
}