# Asignar comisionista a Usuario

Generico:

POST http://localhost:3000/api/advisor/assign/:advisorId
Authorization: Bearer <token_de_usuario>

Ej:
POST http://localhost:3000/api/advisor/assign/100038954
Authorization: Bearer <token_de_usuario>

Response:

{
  "id": 1,
  "clientId": "100039482",
  "advisorId": "100038954",
  "assigned_at": "2025-06-15T19:03:09.246Z",
  "updated_at": "2025-06-15T19:03:09.246Z",
  "is_active": true
}

*Se envia un correo notificando al comisionista* 
[Nest] 13324  - 06/20/2025, 10:30:56 PM     LOG [NotificationsService] Trabajo de notificación encolado para: 3
[Nest] 13324  - 06/20/2025, 10:30:56 PM     LOG [AdvisorService] Notificación encolada para el comisionista: 3
[Nest] 13324  - 06/20/2025, 10:30:58 PM     LOG [MailService] Email enviado a: kakisitote@gmail.com
[Nest] 13324  - 06/20/2025, 10:30:58 PM     LOG [NotificationProcessor] Notificación enviada al comisionista: 3