PATCH /api/users/987654321 HTTP/1.1
Content-Type: application/json
User-Agent: insomnia/11.1.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiY2RjYXNhc2RAdWRpc3RyaXRhbC5lZHUuY28iLCJ1c2VySWQiOiI5ODc2NTQzMjEiLCJyb2xlcyI6WyJhZG1pbiIsInVzdWFyaW9fcHJlbWl1bSJdLCJpYXQiOjE3NTA5ODg1ODMsImV4cCI6MTc1MDk5MjE4M30.GNmxZO2MIPDWNDiPbsbQ3MgAYBJ3RV3CM6oqwt7ks8o
Host: localhost:3000
Content-Length: 100

PATCH /api/users/{aca va el identity del usuario} HTTP/1.1


{
  "phone": "3101234588",
  "email": "cdcasasd@udistrital.edu.co",
  "address": "Nueva dirección"
}

response:

{
	"message": "Usuario actualizado",
	"user": {
		"message": "Perfil actualizado correctamente",
		"email": "cdcasasd@udistrital.edu.co",
		"phone": "3101234588"
	}
}